### PR TITLE
Add support for the --open flag the file on linux

### PR DESCRIPTION
**Pull request by latortuga**
Tested the command on Ubuntu Oneiric Ocelot.

### CODE REVIEW

**Comment by beddari** [comment]
Thanks, tested it and it works as expected.

**Comment by igorsobreira** [comment]
Thanks for the contribution @latortuga. 

One problem I see is if you don't find the correct architecture you end up returning `nil`, which will fail on `build_screenshot_options` method, since `nil.empty?` method does not exist.

What I would change is let the `open_command` method return an empty string, or update the verification on `build_screenshot_options`, if no command is detected.

The point is, we should not show the `--open` option if an "open" command is not detected. If the option is not valid, we don't show it on help. And if you use, vagrant will fail.

**Comment by latortuga** [comment]
I see what you mean @igorsobreira and it makes a lot of sense so I updated my fix to remove the error printout and instead to return a blank string.

**Comment by latortuga** [comment]
Wow I just realized that the commit message on my first commit is kind of garbled. Sorry about that!

**Comment by igorsobreira** [comment]
Great :)

**Pull request closed without merging**
